<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Bis-Mac-mini.local" failures="0" tests="19" name="TestCases.TS005_EmailScripts04" time="838.025" errors="5" timestamp="05 Mar 2019 22:47:13 GMT" skipped="12">
  <testcase classname="TestCases.TS005_EmailScripts04" name="TS005_EmailScripts04_Email4_createNewVIPContactFromDetail" time="8.984">
    <skipped/>
  </testcase> <!-- TS005_EmailScripts04_Email4_createNewVIPContactFromDetail -->
  <testcase classname="TestCases.TS005_EmailScripts04" name="TS005_EmailScripts04_Email5_addToExistingContactFromDetail" time="8.967">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at Keywords.CommonKeywords.clickViewBottomBar(CommonKeywords.java:1208)
	at TestCases.TS005_EmailScripts04.TS005_EmailScripts04_Email5_addToExistingContactFromDetail(TS005_EmailScripts04.java:245)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
    </error>
  </testcase> <!-- TS005_EmailScripts04_Email5_addToExistingContactFromDetail -->
  <testcase classname="TestCases.TS005_EmailScripts04" name="TS005_EmailScripts04_Email3_createNewContactFromDetail" time="16.429">
    <skipped/>
  </testcase> <!-- TS005_EmailScripts04_Email3_createNewContactFromDetail -->
  <testcase classname="TestCases.TS005_EmailScripts04" name="TS005_EmailScripts04_Email3_createNewContactFromDetail" time="4.955">
    <skipped/>
  </testcase> <!-- TS005_EmailScripts04_Email3_createNewContactFromDetail -->
  <testcase classname="TestCases.TS005_EmailScripts04" name="TS005_EmailScripts04_Email3_createNewContactFromDetail" time="4.706">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at Keywords.CommonKeywords.openNewItemView(CommonKeywords.java:1345)
	at TestCases.TS005_EmailScripts04.TS005_EmailScripts04_Email3_createNewContactFromDetail(TS005_EmailScripts04.java:184)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
    </error>
  </testcase> <!-- TS005_EmailScripts04_Email3_createNewContactFromDetail -->
  <testcase classname="TestCases.TS005_EmailScripts04" name="TS005_EmailScripts04_Email4_createNewVIPContactFromDetail" time="9.154">
    <skipped/>
  </testcase> <!-- TS005_EmailScripts04_Email4_createNewVIPContactFromDetail -->
  <testcase classname="TestCases.TS005_EmailScripts04" name="TS005_EmailScripts04_Email3_createNewContactFromDetail" time="4.642">
    <skipped/>
  </testcase> <!-- TS005_EmailScripts04_Email3_createNewContactFromDetail -->
  <testcase classname="TestCases.TS005_EmailScripts04" name="TS005_EmailScripts04_Email0_checkEmailInVipFilter" time="257.569"/>
  <testcase classname="TestCases.TS005_EmailScripts04" name="TS005_EmailScripts04_Email2_updateEmailListAfterDeleteContact" time="31.384">
    <skipped/>
  </testcase> <!-- TS005_EmailScripts04_Email2_updateEmailListAfterDeleteContact -->
  <testcase classname="TestCases.TS005_EmailScripts04" name="TS005_EmailScripts04_Email5_addToExistingContactFromDetail" time="9.062">
    <skipped/>
  </testcase> <!-- TS005_EmailScripts04_Email5_addToExistingContactFromDetail -->
  <testcase classname="TestCases.TS005_EmailScripts04" name="TS005_EmailScripts04_Email2_updateEmailListAfterDeleteContact" time="29.278">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at Keywords.ContactKeywords.deleteContactBySwipe(ContactKeywords.java:378)
	at TestCases.TS005_EmailScripts04.TS005_EmailScripts04_Email2_updateEmailListAfterDeleteContact(TS005_EmailScripts04.java:159)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
    </error>
  </testcase> <!-- TS005_EmailScripts04_Email2_updateEmailListAfterDeleteContact -->
  <testcase classname="TestCases.TS005_EmailScripts04" name="TS005_EmailScripts04_Email4_createNewVIPContactFromDetail" time="9.002">
    <skipped/>
  </testcase> <!-- TS005_EmailScripts04_Email4_createNewVIPContactFromDetail -->
  <testcase classname="TestCases.TS005_EmailScripts04" name="TS005_EmailScripts04_Email2_updateEmailListAfterDeleteContact" time="29.745">
    <skipped/>
  </testcase> <!-- TS005_EmailScripts04_Email2_updateEmailListAfterDeleteContact -->
  <testcase classname="TestCases.TS005_EmailScripts04" name="TS005_EmailScripts04_Email5_addToExistingContactFromDetail" time="9.099">
    <skipped/>
  </testcase> <!-- TS005_EmailScripts04_Email5_addToExistingContactFromDetail -->
  <testcase classname="TestCases.TS005_EmailScripts04" name="TS005_EmailScripts04_Email2_updateEmailListAfterDeleteContact" time="115.465">
    <skipped/>
  </testcase> <!-- TS005_EmailScripts04_Email2_updateEmailListAfterDeleteContact -->
  <testcase classname="TestCases.TS005_EmailScripts04" name="TS005_EmailScripts04_Email4_createNewVIPContactFromDetail" time="8.943">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at Keywords.CommonKeywords.clickViewBottomBar(CommonKeywords.java:1208)
	at TestCases.TS005_EmailScripts04.TS005_EmailScripts04_Email4_createNewVIPContactFromDetail(TS005_EmailScripts04.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
    </error>
  </testcase> <!-- TS005_EmailScripts04_Email4_createNewVIPContactFromDetail -->
  <testcase classname="TestCases.TS005_EmailScripts04" name="TS005_EmailScripts04_Email1_checkEmailInStarFilter" time="262.732"/>
  <testcase classname="TestCases.TS005_EmailScripts04" name="clearUp" time="9.081">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at Keywords.CommonKeywords.clickViewBottomBar(CommonKeywords.java:1208)
	at TestCases.TS005_EmailScripts04.clearUp(TS005_EmailScripts04.java:276)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:212)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
    </error>
  </testcase> <!-- clearUp -->
  <testcase classname="TestCases.TS005_EmailScripts04" name="TS005_EmailScripts04_Email5_addToExistingContactFromDetail" time="8.828">
    <skipped/>
  </testcase> <!-- TS005_EmailScripts04_Email5_addToExistingContactFromDetail -->
</testsuite> <!-- TestCases.TS005_EmailScripts04 -->
